###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID user3.nielitchennai.edu.in)
#  Generated on:      Fri Apr 25 12:39:00 2025
#  Design:            calculator_fsm
#  Command:           create_ccopt_clock_tree_spec -file ccopt_output.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clk (period 12.000ns) in timing_config SDC([alu_fsm_output.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner MIN -early -clock_tree clk 0.200
set_ccopt_property target_max_trans_sdc -delay_corner MIN -late -clock_tree clk 0.200
set_ccopt_property source_output_max_trans -delay_corner MIN -early -clock_tree clk 0.100
set_ccopt_property source_output_max_trans -delay_corner MAX -early -clock_tree clk 0.100
set_ccopt_property source_output_max_trans -delay_corner MIN -late -clock_tree clk 0.100
set_ccopt_property source_output_max_trans -delay_corner MAX -late -clock_tree clk 0.100
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 12

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:SDC (sdc alu_fsm_output.sdc)
create_ccopt_skew_group -name clk/SDC -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/SDC true
set_ccopt_property extracted_from_clock_name -skew_group clk/SDC clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/SDC SDC
set_ccopt_property extracted_from_delay_corners -skew_group clk/SDC {MIN MAX}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

